version: '3.5'
services:

  postgres:
    image: postgres:16.1-alpine3.19
    container_name: patient_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: "Europe/Minsk"
      PGTZ: "Europe/Minsk"
    command: postgres -c max_connections=1000
    ports:
      - "5452:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5